# Generated by Django 5.2 on 2025-04-23 18:40

import django.db.models.deletion
import ticketing_system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkingUserToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.PositiveIntegerField(choices=[(1, 'DRAFT'), (2, 'ONGOING'), (3, 'COMPLETED'), (4, 'ARCHIVED')], default=1)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_projects', through='ticketing_system.LinkingUserToProject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='linkingusertoproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='ticketing_system.project'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.PositiveIntegerField(choices=[(1, 'DRAFT'), (2, 'ONGOING'), (3, 'COMPLETED'), (4, 'ARCHIVED')], default=1)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ticketing_system.models.ticket_attachment_upload_path)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticketing_system.ticket')),
            ],
        ),
    ]
